- name: Deploy to Kubernetes using Ansible
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault/secrets.yml

  tasks:
    - name: Render backend deployment template with secrets
      template:
        src: manifests/backend-deployment.yaml.j2
        dest: "{{ playbook_dir }}/../k8s/backend-deployment.yaml"

    - name: Apply backend deployment manifest
      shell: kubectl apply -f backend-deployment.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}/../k8s"

    - name: Expose backend
      shell: kubectl apply -f manifests/backend-service.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Deploy ml-service
      shell: kubectl apply -f manifests/ml-deployment.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Expose ml-service
      shell: kubectl apply -f manifests/ml-service.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Deploy frontend
      shell: kubectl apply -f manifests/frontend-deployment.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Expose frontend
      shell: kubectl apply -f manifests/frontend-service.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Apply backend HPA
      shell: kubectl apply -f manifests/backend-hpa.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Apply ml-service HPA
      shell: kubectl apply -f manifests/ml-service-hpa.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    - name: Apply frontend HPA
      shell: kubectl apply -f manifests/frontend-hpa.yaml --kubeconfig /absolute/path/to/kubeconfig
      args:
        chdir: "{{ playbook_dir }}"

    # ------------------------------------
    # ELK Stack Setup for Log Integration
    # ------------------------------------

    - name: Copy Logstash config
      ansible.builtin.copy:
        src: elk/logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Logstash
      ansible.builtin.systemd:
        name: logstash
        state: restarted
        enabled: true

    - name: Wait for Logstash to be ready
      ansible.builtin.wait_for:
        port: 5044
        timeout: 30
        state: started

    - name: Import Kibana dashboard (optional)
      ansible.builtin.uri:
        url: "http://localhost:5601/api/saved_objects/_import?overwrite=true"
        method: POST
        headers:
          kbn-xsrf: "true"
        body: "{{ lookup('file', 'elk/dashboard.ndjson') }}"
        body_format: raw
      when: dashboard_import is defined and dashboard_import

    - name: Create Kibana index pattern (optional)
      ansible.builtin.uri:
        url: "http://localhost:5601/api/saved_objects/index-pattern/backend-logs"
        method: POST
        headers:
          kbn-xsrf: "true"
        body: "{{ lookup('file', 'elk/kibana-index-pattern.json') }}"
        body_format: json
      when: index_pattern_create is defined and index_pattern_create
